In [1]:
import tensorflow as tf

In [2]:
numbers = [21,32,43,54, -23, 67, -12,108]

In [3]:
tf_dataset = tf.data.Dataset.from_tensor_slices(numbers)
tf_dataset

<TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [4]:
for sales in tf_dataset:
    print(sales.numpy())

21
32
43
54
-23
67
-12
108


In [5]:
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

21
32
43
54
-23
67
-12
108


In [6]:
for sales in tf_dataset.take(2):
    print(sales.numpy())

21
32


In [7]:
tf_dataset = tf_dataset.filter(lambda x: x>0)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

21
32
43
54
67
108


In [8]:
tf_dataset = tf_dataset.map(lambda x: x*102)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

2142
3264
4386
5508
6834
11016


In [9]:
tf_dataset = tf_dataset.shuffle(2)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

3264
4386
5508
6834
2142
11016


In [10]:
tf_dataset = tf_dataset.batch(3)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

[2142 4386 5508]
[ 6834 11016  3264]


In [12]:
numbers = [21,32,43,54, -23, 67, -12,108]
tf_dataset = tf.data.Dataset.from_tensor_slices(numbers)
tf_dataset = tf_dataset.filter(lambda x: x>0).map(lambda y: y*102).shuffle(2).batch(3)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

[3264 2142 4386]
[ 5508  6834 11016]
